version: '3.7'

networks:
  default:
    name: jsontoKafkanet

volumes:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:


services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    restart: unless-stopped
    container_name: "zookeeper"
    hostname: "zookeeper"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    restart: unless-stopped
    container_name: "kafka"
    hostname: "kafka"
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'   
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
